version: "3"
services:
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper-pizzashop
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks: 
      - pizzashop
  pinot-controller:
    image: apachepinot/pinot:0.12.0-arm64
    command: "StartController -zkAddress zookeeper-pizzashop:2181"
    container_name: "pinot-controller"
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    healthcheck: {test: nc -z localhost 9000, interval: 1s}
    networks: 
      - pizzashop
  pinot-broker:
    image: apachepinot/pinot:0.12.0-arm64
    command: "StartBroker -zkAddress zookeeper-pizzashop:2181"
    restart: unless-stopped
    container_name: "pinot-broker"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks: 
      - pizzashop
  pinot-server:
    image: apachepinot/pinot:0.12.0-arm64
    container_name: "pinot-server"
    command: "StartServer -zkAddress zookeeper-pizzashop:2181"
    restart: unless-stopped
    depends_on:
      - pinot-broker
    networks: 
      - pizzashop
  pinot-add-table:
    image: apachepinot/pinot:0.12.0-arm64
    container_name: "pinot-add-table"
    volumes:
      - ./pinot/config:/config
      - ./scripts/:/scripts
    command: "/scripts/add_tables.sh"
    restart: on-failure
    entrypoint: "bash -c"
    environment:
    - "JAVA_OPTS=-Dpinot.admin.system.exit=true"
    depends_on:
      - pinot-controller
    networks: 
      - pizzashop
networks:
  pizzashop:
    name: pizzashop